config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "photos#index"
  resources :photos, only:[:index] do
    collection do
      get 'page'
      get 'tags'
      post 'uploadpicture'
      post 'update_photo_tag'
      post 'drag_photo_tag'
    end

  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/employment.rb
class Employment
  include Mongoid::Document
  include Mongoid::Timestamps

  field :title, type: String
  field :commany_name, type: String
  field :url,type: String
  field :url_from, type:String

end

app/models/photo.rb
class Photo
  include Mongoid::Document
  include Mongoid::Timestamps

  has_and_belongs_to_many :tags, autosave: true

  before_save :add_tag

  field :title, type: String, default: "" #title

  def tag_title
    tag_title = "  "
    self.tags.each{|tag| tag_title << (tag.title + " ")}
    tag_title
  end
  def tag_title_array
    tag_title_array = []
    self.tags.each{|tag| tag_title_array << tag.title }
    tag_title_array
  end
  def add_tag
    self.tags << Tag.find_by(:title => 'unTag') if self.tags.blank?
  end
end

app/models/tag.rb
class Tag
  include Mongoid::Document
  include Mongoid::Timestamps

  has_and_belongs_to_many :photos, autosave: true

  field :title, type: String, default: "" #tag

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :set_photo, only: [:drag_photo_tag, :update_photo_tag]
  def index
    agent = Mechanize.new
    agent.user_agent_alias = 'Mac Safari'
    url = URI::escape("https://www.lagou.com/jobs/list_ruby?px=default&city=%E5%85%A8%E5%9B%BD#filterBox")
    page = agent.get url
ap page.links
  end

  def zhilian
    agent = Mechanize.new
    agent.user_agent_alias = 'Mac Safari'
    url = URI::escape("http://news.qq.com/a/20170815/035706.htm")
    page = agent.get url
    agent.open_timeout=10
    page.encoding='utf-8'
    ap page
    page.save(page.html)
    links = page.links
    # uripage = agent.get 'http://jobs.zhaopin.com/677618624250490.htm'
    # ap uripage.title()
    # links.each_with_index  do |link,index|
    #   uri = link.uri()
      #uripage = agent.get uri if (uri.to_s.include? 'jobs.zhaopin.com') && (uri.to_s.split('.').last.include? 'htm')
      # if uripage.present?
      #   title_array = uripage.title.split('-')
      #   if title_array.size == 2
      #     name_array = title_array[0].split('_')
      #     if name_array.size == 2
      #       Employment.find_or_create_by(:title => name_array[0].gsub('【',''),
      #                                    :commany_name => name_array[1].gsub('人才招聘信息】',''),
      #                                    :url => uri.to_s,:url_from => title_array[1])
      #     end
      #   end
      # end

    # end
  end


  def tags
    @tags = Tag.all
    render :partial => 'tag'
  end

  def uploadpicture
    qiniu   = QiniuConfig.upload(params[:fileUp].path,params[:fileName])
    Photo.create(:title => qiniu[:result]["key"])
    @tags   = Tag.all
    @photos = Photo.all.page(1).per(9)
    render :index
  end

  def drag_photo_tag
    tag = Tag.find(params[:tag_id])

    @photo.tags << tag unless @photo.tags.include? tag
    tag.photos << @photo unless tag.photos.include? @photo

    respond_to do |format|
      format.json { render json: {message: "ok"}, status: :ok }
    end
  end

  def update_photo_tag
    if params[:tag_title].present?
      tag = Tag.find_or_create_by(:title => params[:tag_title])
      @photo.tags.clear
      #photo.save
      @photo.tags << tag
    end
    respond_to do |format|
      format.json { render json: {message: "ok"}, status: :ok }
    end
  end

  def page
    if params[:tag_id].present?
      tag        = Tag.find(params[:tag_id])
      @tag_title = tag.title
      photos     = tag.photos
    else
      @tag_title = 'All'
      photos     = Photo.all
    end
    @photos = photos.page(params[:page]).per(9)
    #binding.pry
    render :partial => 'photo'
  end

  def set_photo
    @photo = Photo.find(params[:photo_id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MeizuTest</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/photos/_photo.html.erb
<div class="photo_div">
  <span>Photo in <strong><%= @tag_title %></strong></span>
</div>
<div class="show_photo_all">
  <% @photos.each do |photo| %>
      <div class="show_photo">
        <div class="pic" draggable="true"  ondragstart="dragStar(event)">
          <img src="<%= QiniuConfig.full_url(photo.title) %>" id="<%= photo.id %>" class="img" >
        </div>
        <div class="title">
          <div class="r_title">
            Title:<%= photo.title %>
          </div>
          <div class="r_title">
            Date:<%= photo.created_at.strftime("%Y/%m/%d") %>
          </div>
          <div class="r_title">
            Tag:<span id = "ol<%= photo.id %>" onclick="change_tag(this)" style="display: block"><%= photo.tag_title %></span>
          </div>
        </div>
      </div>
  <% end %>
  <div class="release_fenye">
    <% if @photos.count > 9 %>Page:&nbsp;<% end %>
    <%= paginate @photos,:theme => 'photo_pagination'%>
  </div>
</div>

app/views/photos/_tag.html.erb
<div class="label">
  <label >Tags</label>
</div>
<% @tags.each do |tag| %>
    <div class="tag_title" id = "<%= tag.id %>" ondragenter="dragente(event)" ondragover="dragove(event)" ondrop="onDro(event)">
      <span class="tag_title_span">>&nbsp;</span>
      <a href="javascript:void(0);" class="tag_title_a" id="<%= tag.id %>" onclick="set_and_find(this)"><%= tag.title %></a>
      <input type="hidden" id="choos_tag" value="">
    </div>
<% end %>
<div class="upload">

  <%= form_tag(uploadpicture_photos_path,method: :post,enctype: "multipart/form-data",target: 'frameFile') do %>
      <input type="file" name="fileUp" accept="image/png,image/gif,image/jpeg" value="" alt="" onchange="upload(this)" style = "display:none" id = "fileUp" />
      <input type="text" name="fileName" style = "display:none" value="" id = "fileName" />
      <div onclick="setpic(this)">upload photo </div>
      <%= button_tag "提交", id:"picbutt",style:"display:none" %>
  <% end %>
  <iframe id='frameFile' name='frameFile' style='display: none;'></iframe>

</div>

app/views/photos/index.html.erb
<div style="width: 100%;">
  <div class="tag">

  </div>
  <div class="photo">

  </div>
</div>
<div id = "uploadpage"></div>


<script>
console.log(Base64.encode('11111'));
</script>